version: "3.8"
services:
 db:
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_DB: $POSTGRES_NAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    restart: always
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready --username=$POSTGRES_USER -d $POSTGRES_NAME' ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pg_data:/var/lib/postgresql/data

 api:
    image: dsvistelnik/todolist
    ports:
      - '80:80'
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

 front:
    image: sermalenk/skypro-front:lesson-34
    depends_on:
      - api
    ports:
      - '80:80'
