version: '3.8'

services:
  front:
    build:
      context: .
    depends_on:
      - api
    ports:
      - '80:80'

  api:
    build:
      context: .
    expose:
      - 8000
    depends_on:
      migrations:
        condition: service_completed_successfully

  migrations:
    build:
      context: .
    command: flask db upgrade
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 3s
      timeout: 3s
      retries: 5
    ports:
      - "5432:5432"

volumes:
   pg_data: