version: '3.8'

services:
 db:
   image: postgres:14.1-alpine
   restart: always
   volumes:
    - pg_data:/var/lib/postgresql/data
   healthcheck:
    test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
    interval: 3s
    timeout: 3s
    retries: 5


 api:

    build:
      context: .
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy



 front:
   image: sermalenk/skypro-front:lesson-34
   ports:
     - "80:80"
   depends_on:
      api:
        condition: service_started


volumes:
   pg_data:
