version: '3.8'

services:
  front:
    image: sermalenk/skypro-front:lesson-34
    ports:
        - "80:80"
    depends_on:
        api:
          condition: service_started

  api:
    build:
      context: .
    expose:
      - 8000
    depends_on:
      migrations:
        condition: service_completed_successfully

  migrations:
    build:
      context: .
    command: flask db upgrade
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.1-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 3s
      timeout: 3s
      retries: 5
    ports:
      - "5432:5432"

volumes:
   pg_data: