version: "3.8"
services:
 db:
    image: postgres:latest
    expose:
      - 5432
    env_file: .env
    restart: always
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready --username=postgres -d postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pg_data:/var/lib/postgresql/data

 api:
    image: dsvistelnik/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

 front:
    image: sermalenk/skypro-front:lesson-36
    depends_on:
      - api
    ports:
      - '80:80'
