version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    expose:
      - 5432
    environment:
      POSTGRES_DB: $POSTGRES_NAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready --username=$POSTGRES_USER -d $POSTGRES_NAME']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
