# Generated by Django 4.0.1 on 2023-05-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_alter_board_options_alter_board_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
