# Generated by Django 4.0.1 on 2023-05-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_alter_board_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Доска', 'verbose_name_plural': 'Доски'},
        ),
        migrations.AlterField(
            model_name='board',
            name='created',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='board',
            name='updated',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='goalcategory',
            name='created',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='goalcategory',
            name='updated',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего обновления'),
        ),
    ]
