name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_NAME: ${{secrets.POSTGRES_NAME}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
    steps:     
      - name: clone git repo
        uses: actions/checkout@v2
      - name: build api image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/todolist:api-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{secrets.DOCKERHUB_TOKEN}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      - name: docker push images
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/todolist:api-$GITHUB_RUN_ID


  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_USER }}
      DB_NAME: ${{ secrets.DB_USER }}
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: render docker-compose
        run: |
          cat docker-compose-ci.yaml | envsubst > todolist/docker-compose.yaml
      - name: copy docker-compose.yaml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.NAME_SKYPRO }}
          password: ${{ secrets.SKYPRO_PASSWORD }}
          source: "todolist/docker-compose.yaml"
          target: todolist
          strip_components: 1

      - name: run docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.NAME_SKYPRO }}
          password: ${{ secrets.SKYPRO_PASSWORD }}
          script: |
            cd todolist
            echo ${{ secrets.SKYPRO_PASSWORD }} | sudo -S docker-compose up -d
