name: todolist
on: [push]
jobs:
  build_images:
    runs-on: ubuntu-latest
    env:
      POSTGRES_NAME: ${{secrets.POSTGRES_NAME}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}

    steps:
      - name: clone git repo
        uses: actions/checkout@v2
      - name: build api image
        run: docker build -t dsvistelnik/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{secrets.DOCKER_TOKEN}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - name: docker push images
        run: docker push dsvistelnik/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID .